"""Sync models with database

Revision ID: 40f5473e5b23
Revises: 0001_tenant_dashboard_schema
Create Date: 2026-02-02 17:09:16.540216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
import models

# revision identifiers, used by Alembic.
revision: str = '40f5473e5b23'
down_revision: Union[str, None] = '0001_tenant_dashboard_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_index('idx_audit_log_tenant', table_name='audit_log')
    op.alter_column('budgets', 'expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('budgets', 'remaining_points')
    op.drop_constraint('department_budgets_budget_id_department_id_key', 'department_budgets', type_='unique')
    op.drop_column('department_budgets', 'remaining_points')
    op.drop_constraint('departments_tenant_id_name_key', 'departments', type_='unique')
    op.drop_index('idx_feed_tenant_created', table_name='feed')
    op.drop_index('idx_login_otps_email', table_name='login_otps')
    op.create_index(op.f('ix_login_otps_email'), 'login_otps', ['email'], unique=False)
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_constraint('recognition_reactions_recognition_id_user_id_reaction_type_key', 'recognition_reactions', type_='unique')
    op.add_column('redemptions', sa.Column('item_type', sa.String(length=20), nullable=False))
    op.add_column('redemptions', sa.Column('item_id', models.GUID(), nullable=True))
    op.add_column('redemptions', sa.Column('item_name', sa.String(length=255), nullable=False))
    op.add_column('redemptions', sa.Column('point_cost', sa.Integer(), nullable=False))
    op.add_column('redemptions', sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('redemptions', sa.Column('markup_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('redemptions', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('redemptions', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('redemptions', sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('redemptions', sa.Column('otp_attempts', sa.Integer(), nullable=True))
    op.add_column('redemptions', sa.Column('delivery_details', models.JSONType(), nullable=True))
    op.add_column('redemptions', sa.Column('tracking_number', sa.String(length=255), nullable=True))
    op.add_column('redemptions', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('redemptions', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('redemptions', sa.Column('failed_reason', sa.Text(), nullable=True))
    op.alter_column('redemptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('redemptions', 'voucher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('redemptions_voucher_id_fkey', 'redemptions', type_='foreignkey')
    op.drop_constraint('redemptions_user_id_fkey', 'redemptions', type_='foreignkey')
    op.create_foreign_key(None, 'redemptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'redemptions', 'vouchers', ['voucher_id'], ['id'], ondelete='SET NULL')
    op.drop_column('redemptions', 'voucher_pin')
    op.drop_column('redemptions', 'expires_at')
    op.drop_column('redemptions', 'provider_reference')
    op.drop_column('redemptions', 'fulfilled_at')
    op.drop_column('redemptions', 'copay_amount')
    op.drop_column('redemptions', 'points_used')
    op.drop_constraint('tenant_vouchers_tenant_id_voucher_id_key', 'tenant_vouchers', type_='unique')
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('favicon_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('theme_config', models.JSONType(), nullable=True))
    op.add_column('tenants', sa.Column('domain_whitelist', models.JSONType(), nullable=True))
    op.add_column('tenants', sa.Column('auth_method', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('currency_label', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('conversion_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('tenants', sa.Column('auto_refill_threshold', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('award_tiers', models.JSONType(), nullable=True))
    op.add_column('tenants', sa.Column('peer_to_peer_enabled', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('expiry_policy', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('org_role', sa.String(length=50), nullable=False, server_default='employee'))
    op.drop_constraint('users_tenant_id_email_key', 'users', type_='unique')
    op.drop_index('idx_wallet_ledger_created_at', table_name='wallet_ledger')
    op.drop_index('idx_wallet_ledger_wallet_id', table_name='wallet_ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_wallet_ledger_wallet_id', 'wallet_ledger', ['wallet_id'], unique=False)
    op.create_index('idx_wallet_ledger_created_at', 'wallet_ledger', ['created_at'], unique=False)
    op.create_unique_constraint('users_tenant_id_email_key', 'users', ['tenant_id', 'email'])
    op.drop_column('users', 'org_role')
    op.drop_column('tenants', 'expiry_policy')
    op.drop_column('tenants', 'peer_to_peer_enabled')
    op.drop_column('tenants', 'award_tiers')
    op.drop_column('tenants', 'auto_refill_threshold')
    op.drop_column('tenants', 'conversion_rate')
    op.drop_column('tenants', 'currency_label')
    op.drop_column('tenants', 'auth_method')
    op.drop_column('tenants', 'domain_whitelist')
    op.drop_column('tenants', 'theme_config')
    op.drop_column('tenants', 'favicon_url')
    op.drop_column('tenants', 'logo_url')
    op.create_unique_constraint('tenant_vouchers_tenant_id_voucher_id_key', 'tenant_vouchers', ['tenant_id', 'voucher_id'])
    op.add_column('redemptions', sa.Column('points_used', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('redemptions', sa.Column('copay_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('redemptions', sa.Column('fulfilled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('redemptions', sa.Column('provider_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('redemptions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('redemptions', sa.Column('voucher_pin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'redemptions', type_='foreignkey')
    op.drop_constraint(None, 'redemptions', type_='foreignkey')
    op.create_foreign_key('redemptions_user_id_fkey', 'redemptions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('redemptions_voucher_id_fkey', 'redemptions', 'vouchers', ['voucher_id'], ['id'])
    op.alter_column('redemptions', 'voucher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('redemptions', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('redemptions', 'failed_reason')
    op.drop_column('redemptions', 'shipped_at')
    op.drop_column('redemptions', 'processed_at')
    op.drop_column('redemptions', 'tracking_number')
    op.drop_column('redemptions', 'delivery_details')
    op.drop_column('redemptions', 'otp_attempts')
    op.drop_column('redemptions', 'otp_verified_at')
    op.drop_column('redemptions', 'otp_expires_at')
    op.drop_column('redemptions', 'otp_code')
    op.drop_column('redemptions', 'markup_amount')
    op.drop_column('redemptions', 'actual_cost')
    op.drop_column('redemptions', 'point_cost')
    op.drop_column('redemptions', 'item_name')
    op.drop_column('redemptions', 'item_id')
    op.drop_column('redemptions', 'item_type')
    op.create_unique_constraint('recognition_reactions_recognition_id_user_id_reaction_type_key', 'recognition_reactions', ['recognition_id', 'user_id', 'reaction_type'])
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_login_otps_email'), table_name='login_otps')
    op.create_index('idx_login_otps_email', 'login_otps', ['email'], unique=False)
    op.create_index('idx_feed_tenant_created', 'feed', ['tenant_id', sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('departments_tenant_id_name_key', 'departments', ['tenant_id', 'name'])
    op.add_column('department_budgets', sa.Column('remaining_points', sa.NUMERIC(precision=15, scale=2), sa.Computed('(allocated_points - spent_points)', persisted=True), autoincrement=False, nullable=True))
    op.create_unique_constraint('department_budgets_budget_id_department_id_key', 'department_budgets', ['budget_id', 'department_id'])
    op.add_column('budgets', sa.Column('remaining_points', sa.NUMERIC(precision=15, scale=2), sa.Computed('(total_points - allocated_points)', persisted=True), autoincrement=False, nullable=True))
    op.alter_column('budgets', 'expiry_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.create_index('idx_audit_log_tenant', 'audit_log', ['tenant_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
